import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {validateSourceBundle,sourceBundleDigest,validateSourcePath} from './source-checkpoints.mjs';
import {operateJob} from './jobs.mjs';
const hash=x=>createHash('sha256').update(x).digest('hex');
export const identity={repository:'lrnolivia/relay',branch:'relay/source-fixture',head_sha:'a'.repeat(40),scope:['src/']};
export function bundleOf(text='first source',name='src/example.js'){const bytes=Buffer.from(text);return {schema:1,...identity,files:[{path:name,kind:'file',mode:420,size:bytes.length,sha256:hash(bytes),data:bytes.toString('base64')}]};}
export function sourceFixture(){
 const objects=new Map();let now=Date.parse('2026-10-07T00:00:00Z'),seq=0,op=0,job,token;
 const bucket={get:async key=>{const obj=objects.get(key);return obj?{etag:obj.etag,json:async()=>JSON.parse(obj.text)}:null;},put:async(key,text,{onlyIf})=>{const old=objects.get(key);if(onlyIf instanceof Headers?Boolean(old):old?.etag!==onlyIf.etagMatches)return null;const etag=String(++seq);objects.set(key,{text,etag});return {etag};}};
 const target={state:'active',owner:'owner',branch:identity.branch,repository:identity.repository,head_sha:identity.head_sha,lease_until:'2099-01-01T00:00:00Z',goal:'Preserve source',acceptance:['Exact restore'],paths:identity.scope};
 const common={project:'relay',assignment:'source-fixture',expected_owner:'owner',expected_branch:identity.branch};
 const call=async(action,extra={})=>{const result=await operateJob(bucket,{...common,action,operation_id:'op-'+(++op),...(job?{job_id:job.id,expected_revision:job.revision}:{}),executor_id:'fixture',...(token?{lease_token:token}:{}),...extra},target,{now,uuid:()=> 'fixture-lease'});job=result.job;token=result.lease_token||token;return result;};
 const begin=async()=>{await call('submit',{prompt:'Exact scope',expected_head_sha:identity.head_sha});await call('lease',{capabilities:['codex-cli'],expected_head_sha:identity.head_sha});await call('start',{process:{pid:100,host:'offline',version:'synthetic',adapter:'codex-cli'}});};
 return {objects,bucket,target,common,call,begin,write:b=>call('checkpoint',{checkpoint:{head_sha:identity.head_sha,summary:'capture',source_bundle:b}}),ack:r=>call('checkpoint',{checkpoint:{head_sha:identity.head_sha,summary:'restored',source_restore:r}}),read:()=>call('source_read'),advance:()=>{now+=300001;},get job(){return job;},get token(){return token;}};
}
test('manifest binds bytes, identity and scope',()=>{const b=bundleOf();assert.equal(validateSourceBundle(b,identity).digest,sourceBundleDigest(b));for(const key of ['repository','branch','head_sha'])assert.throws(()=>validateSourceBundle(b,{...identity,[key]:'wrong'}));assert.throws(()=>validateSourceBundle({...b,scope:['other/']},identity));});
test('corrupt bytes, sizes, digest, base64 and modes fail closed',()=>{for(const delta of [{size:900},{sha256:'b'.repeat(64)},{data:'@@@@'},{mode:511}]){const b=bundleOf();Object.assign(b.files[0],delta);assert.throws(()=>validateSourceBundle(b,identity));}});
test('secret/control paths, traversal, aliases, credentials and oversized captures are excluded',()=>{for(const p of ['../x','/root/x','a/../b','.git/config','.env','src/.env.local','src/a.pem','src/AGENTS.md','src/a\\b','src/CON','src/name.'])assert.throws(()=>validateSourcePath(p),p);for(const text of ['-----BEGIN '+'PRIVATE KEY-----','ghp_'+ 'a'.repeat(36)])assert.throws(()=>validateSourceBundle(bundleOf(text),identity),/credential/);assert.throws(()=>validateSourceBundle(bundleOf('a'.repeat(128*1024+1)),identity));});
test('exact file omissions and parent collisions fail closed',()=>{assert.throws(()=>validateSourceBundle({...bundleOf(),scope:['src/example.js'],files:[]},{...identity,scope:['src/example.js']}),/missing/);assert.throws(()=>validateSourceBundle({...bundleOf(),files:[bundleOf('a','src/a').files[0],bundleOf('b','src/a/b').files[0]]},identity),/parent/);});
test('private checkpoint has server readback; status never returns source bytes',async()=>{const f=sourceFixture();await f.begin();const b=bundleOf(),r=await f.write(b);assert.equal(r.job.checkpoint.source.state,'remote_verified');assert.equal(JSON.stringify(r).includes(b.files[0].data),false);assert.equal(r.job._source_checkpoint,undefined);assert.deepEqual((await f.read()).source_bundle,b);});
test('restoration requires exact digest/count and labels executor attribution',async()=>{const f=sourceFixture();await f.begin();const digest=sourceBundleDigest(bundleOf());await f.write(bundleOf());await assert.rejects(f.ack({digest,restored_digest:'f'.repeat(64),restored_file_count:1}));await assert.rejects(f.ack({digest,restored_digest:digest,restored_file_count:0}));const r=await f.ack({digest,restored_digest:digest,restored_file_count:1});assert.equal(r.job.checkpoint.source.state,'restore_verified');assert.equal(r.job.checkpoint.source.host_execution_verified,false);});
test('new content invalidates restore; metadata preserves prior bytes without claiming current proof',async()=>{const f=sourceFixture();await f.begin();const digest=sourceBundleDigest(bundleOf());await f.write(bundleOf());await f.ack({digest,restored_digest:digest,restored_file_count:1});let r=await f.call('checkpoint',{checkpoint:{summary:'metadata'}});assert.equal(r.job.checkpoint.source.state,'local_only');assert.equal(r.job.checkpoint.last_verified_source.state,'restore_verified');r=await f.write(bundleOf('second'));assert.equal(r.job.checkpoint.source.state,'remote_verified');assert.notEqual(r.job.checkpoint.source.digest,digest);});
test('missing readback preserves prior receipt; corrupt stored bytes never return',async()=>{const f=sourceFixture();await f.begin();await f.write(bundleOf());const prior=f.job.checkpoint.source.digest,oldGet=f.bucket.get;f.bucket.get=async key=>key.includes(sourceBundleDigest(bundleOf('second')))?null:oldGet(key);await assert.rejects(f.write(bundleOf('second')),/missing/);f.bucket.get=oldGet;assert.equal((await f.call('status')).job.checkpoint.source.digest,prior);const key=[...f.objects.keys()].find(k=>k.includes(prior));f.objects.set(key,{text:'{}',etag:'corrupt'});await assert.rejects(f.read());});
test('wrong owner, branch, token, revision and scope cannot read private bytes',async()=>{const f=sourceFixture();await f.begin();await f.write(bundleOf());for(const fields of [{expected_owner:'other'},{expected_branch:'relay/other'},{lease_token:'wrong'},{expected_revision:0},{executor_id:'other'}])await assert.rejects(f.call('source_read',fields));f.target.paths=['other/'];await assert.rejects(f.read(),/scope/);});
test('terminal or expired jobs retain read-only recovery after current source advances',async()=>{const f=sourceFixture();await f.begin();const b=bundleOf();await f.write(b);await f.call('finish',{result:{state:'succeeded',exit_code:0,session_id:'session',head_sha:identity.head_sha,summary:'done'}});f.advance();f.target.head_sha='b'.repeat(40);assert.deepEqual((await f.read()).source_bundle,b);await assert.rejects(f.write(bundleOf('later')),/expired|running/);});
test('old snapshots remain readable after a new job without authorizing old mutations',async()=>{const f=sourceFixture();await f.begin();const b=bundleOf();await f.write(b);const old=f.job;await f.call('finish',{result:{state:'failed',exit_code:1,summary:'failed'}});const oldRevision=f.job.revision;await f.call('submit',{expected_head_sha:identity.head_sha,prompt:'new job'});const r=await f.call('source_read',{job_id:old.id,expected_revision:oldRevision});assert.deepEqual(r.source_bundle,b);});
test('caller-supplied proof state and metadata-only saved-source claims are rejected',async()=>{const f=sourceFixture();await f.begin();await assert.rejects(f.call('checkpoint',{checkpoint:{summary:'lie',source:{state:'restore_verified'}}}));const r=await f.call('checkpoint',{checkpoint:{summary:'only filenames',changed_paths:['src/a.js']}});assert.equal(r.job.checkpoint.source.state,'local_only');await assert.rejects(f.read(),/No remotely/);});

test('required capability gates start and successful finish without rejecting legacy jobs',async()=>{const f=sourceFixture();await f.call('submit',{expected_head_sha:identity.head_sha,prompt:'required source',required_capabilities:['codex-cli','source-byte-checkpoints-v1']});await f.call('lease',{expected_head_sha:identity.head_sha,capabilities:['codex-cli','source-byte-checkpoints-v1']});const process={pid:100,host:'fixture',version:'synthetic',adapter:'codex-cli'};await assert.rejects(f.call('start',{process}),/Required source/);const digest=sourceBundleDigest(bundleOf());await f.write(bundleOf());await f.ack({digest,restored_digest:digest,restored_file_count:1});await f.call('start',{process});await f.call('checkpoint',{checkpoint:{summary:'metadata after source changed'}});await assert.rejects(f.call('finish',{result:{state:'succeeded',exit_code:0,session_id:'session',head_sha:identity.head_sha,summary:'done'}}),/Required final/);});

import {readSourceRecoveryHints} from './jobs.mjs';
test('resume recovery metadata contains exact handles and no bytes or token; handoff hides old owner snapshots',async()=>{const f=sourceFixture();await f.begin();const b=bundleOf();await f.write(b);let hints=await readSourceRecoveryHints(f.bucket,'relay',{...f.target,id:'source-fixture'});assert.equal(hints.state,'remote_verified');assert.equal(hints.snapshots[0].job_id,f.job.id);assert.equal(JSON.stringify(hints).includes(b.files[0].data),false);assert.equal(JSON.stringify(hints).includes(f.token),false);hints=await readSourceRecoveryHints(f.bucket,'relay',{...f.target,id:'source-fixture',owner:'other'});assert.deepEqual(hints.snapshots,[]);});
test('ambiguous write reconciles once with same operation without another stored version',async()=>{const f=sourceFixture();await f.begin();const args={...f.common,action:'checkpoint',job_id:f.job.id,expected_revision:f.job.revision,executor_id:'fixture',lease_token:f.token,operation_id:'fixed-operation',checkpoint:{summary:'capture',head_sha:identity.head_sha,source_bundle:bundleOf()}};const first=await operateJob(f.bucket,args,f.target,{now:Date.parse('2026-10-07T00:00:00Z')});const before=[...f.objects].map(([k,v])=>[k,v.etag]);const replay=await operateJob(f.bucket,args,f.target,{now:Date.parse('2026-10-07T00:00:00Z')});assert.equal(replay.replayed,true);assert.equal(replay.job.revision,first.job.revision);assert.deepEqual([...f.objects].map(([k,v])=>[k,v.etag]),before);});

test('required final proof is post-start and bound to the reported exact source head',async()=>{const f=sourceFixture(),b=bundleOf(),digest=sourceBundleDigest(b);await f.call('submit',{expected_head_sha:identity.head_sha,prompt:'required',required_capabilities:['codex-cli','source-byte-checkpoints-v1']});await f.call('lease',{expected_head_sha:identity.head_sha,capabilities:['codex-cli','source-byte-checkpoints-v1']});await f.write(b);await f.ack({digest,restored_digest:digest,restored_file_count:1});await f.call('start',{process:{pid:100,host:'fixture',version:'synthetic',adapter:'codex-cli'}});const result={state:'succeeded',exit_code:0,session_id:'session',head_sha:identity.head_sha,summary:'done'};await assert.rejects(f.call('finish',{result}),/after start/);await f.write(b);await f.ack({digest,restored_digest:digest,restored_file_count:1});await assert.rejects(f.call('finish',{result:{...result,head_sha:'b'.repeat(40)}}),/reported head/);assert.equal((await f.call('finish',{result})).job.state,'succeeded');});

test('recovered required job cannot reuse the previous attempt start as final proof',async()=>{const f=sourceFixture(),b=bundleOf(),digest=sourceBundleDigest(b),proof={digest,restored_digest:digest,restored_file_count:1},process={pid:100,host:'fixture',version:'synthetic',adapter:'codex-cli'},result={state:'succeeded',exit_code:0,session_id:'session',head_sha:identity.head_sha,summary:'done'};await f.call('submit',{expected_head_sha:identity.head_sha,prompt:'required',required_capabilities:['codex-cli','source-byte-checkpoints-v1']});await f.call('lease',{expected_head_sha:identity.head_sha,capabilities:['codex-cli','source-byte-checkpoints-v1']});await f.write(b);await f.ack(proof);await f.call('start',{process});await f.call('finish',{result:{state:'failed',exit_code:1,summary:'interrupted'}});await f.call('recover',{previous_process_stopped:true,checkpoint:{summary:'preserved source'}});await f.write(b);await f.ack(proof);await assert.rejects(f.call('finish',{result}),/after start/);await f.call('start',{process});await assert.rejects(f.call('finish',{result}),/after start/);await f.write(b);await f.ack(proof);assert.equal((await f.call('finish',{result})).job.state,'succeeded');});

import {jobsTool} from './job-control.mjs';
import {validateControlArguments} from '../../../src/runner-control.js';
test('published tool schema admits bounded source recovery and rejects unsupported proof fields',()=>{const base={action:'checkpoint',project:'relay',assignment:'source-fixture',checkpoint:{summary:'capture',head_sha:identity.head_sha,source_bundle:bundleOf()}};assert.doesNotThrow(()=>validateControlArguments(base,jobsTool.inputSchema));assert.doesNotThrow(()=>validateControlArguments({action:'source_read',project:'relay',assignment:'source-fixture'},jobsTool.inputSchema));assert.throws(()=>validateControlArguments({...base,checkpoint:{summary:'lie',source:{state:'restore_verified'}}},jobsTool.inputSchema));});
