import {ProjectIdentity,WorkerIdentity,FeatureIdentity} from './ProjectIdentity';
import {useMosaicOrder} from './useMosaicOrder';
import {MosaicCard} from './MosaicCard';
import {DndContext, closestCenter} from '@dnd-kit/core';
import {SortableContext, rectSortingStrategy} from '@dnd-kit/sortable';
import { useEffect, useState, type CSSProperties } from 'react';
import { useTelemetryMotion } from './useTelemetryMotion';
import { useLiveRelay } from '../live';
import { projectLabel } from '../api';
import { telemetryModel } from '../../public/telemetry-model.js';
const colors=['#f58f76','#46caa0','#efb65d'];
function Icon({kind}:{kind:'play'|'eye'|'target'|'activity'|'pause'}){return <span className={'telemetry-icon icon-'+kind}><svg viewBox="0 0 32 32" fill="none" stroke="currentColor" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{kind==='play'?<path d="m11 7 15 9-15 9Z"/>:kind==='eye'?<><path d="M3 16s5-9 13-9 13 9 13 9-5 9-13 9S3 16 3 16Z"/><circle cx="16" cy="16" r="4"/></>:kind==='target'?<><circle cx="16" cy="16" r="12"/><circle cx="16" cy="16" r="7"/><circle cx="16" cy="16" r="2"/></>:kind==='pause'?<><path d="M12 8v16M21 8v16"/></>:<path d="m4 24 8-12 9 8 7-14"/>}</svg></span>}
function Ring({percent,value,caption}:{percent:number|null;value:string;caption:string}){return <div className="telemetry-ring" aria-label={value+' '+caption}><svg viewBox="0 0 220 220" aria-hidden="true"><circle className="telemetry-track" cx="110" cy="110" r="94"/><circle className="telemetry-arc" cx="110" cy="110" r="94" pathLength="100" strokeDasharray={`${percent??0} 100`} opacity={percent?1:0}/></svg><div><strong>{value}</strong></div><span className="telemetry-ring-caption">{caption}</span></div>}
export function LiveTelemetry({focus}:{focus?:{project:string;assignment:string}}){
 const layout=useMosaicOrder();
 const controls=(key:string)=><div className="telemetry-reorder"><button type="button" aria-label={`move ${key} earlier`} disabled={layout.order.indexOf(key)===0} onClick={()=>layout.step(key,-1)}>←</button><button type="button" aria-label={`move ${key} later`} disabled={layout.order.indexOf(key)===layout.order.length-1} onClick={()=>layout.step(key,1)}>→</button></div>;
 const {allSnapshot:snapshot,state,eventConnected,refresh}=useLiveRelay();const [now,setNow]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const model=telemetryModel(snapshot,now),ready=Boolean(snapshot)&&!snapshot?.loadingProgress?.length&&!snapshot?.failedProgress?.length;
 const age=snapshot?Math.max(0,Math.floor((now-Date.parse(snapshot.fetchedAt))/1000)):null;
 const live=ready&&state==='live'&&age!==null&&age<90;
 const known=Boolean(snapshot&&Object.keys(snapshot.workload||{}).length),observed=known||model.items.length>0;
 const count=(n:number)=>observed?String(n)+(ready?'':'+'):'—';
 const max=Math.max(3,Math.ceil(Math.max(...model.bins)/3)*3);
 const [percent, moving, waiting, needs, products, events, ...bins] = useTelemetryMotion(
  [model.percent??0, model.moving.length, model.waiting.length, model.needs.length, model.projects.length, model.events, ...model.bins.map(n=>164-n/max*124)], observed);
 const value=ready&&model.percent!==null?Math.round(percent)+'%':'—';
 const points=bins.map((y,i)=>[32+i*48,y]),line=points.map(([x,y],i)=>i?`C${(points[i-1][0]+x)/2},${points[i-1][1]} ${(points[i-1][0]+x)/2},${y} ${x},${y}`:`M${x},${y}`).join(' '),area=line+' L560,164 L32,164 Z';
 const href=(project:string,id?:string)=>'https://ctrl.loew.fi/#/runner'+(id?'/'+encodeURIComponent(project)+'/'+encodeURIComponent(id):'?project='+encodeURIComponent(project));
 return <section className="live-telemetry" aria-label="Live workspace telemetry" aria-busy={!snapshot || state==='reconnecting'} data-live={live} data-loading={!snapshot||Boolean(snapshot.loadingProgress?.length)} data-complete={ready}>
  <div className="telemetry-heading"><h2>your workspace <span>/ now</span></h2><button className="telemetry-freshness" type="button" onClick={()=>void refresh()} aria-label="Refresh workspace telemetry"><svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="M20 7v5h-5M4 17v-5h5M19 11a7 7 0 0 0-12-5L4 9m16 6-3 3A7 7 0 0 1 5 13"/></svg><i/>{live?eventConnected?'Live':'Auto refresh':snapshot?state==='reconnecting'?'Refreshing':'Partial or stale':'Connecting'}<span>{age===null?'waiting for records':age<60?`${age}s ago`:`${Math.floor(age/60)}m ago`}</span></button></div>
  {!snapshot&&<p className="telemetry-loading-status" role="status">loading your workspace…</p>}
  <div className="telemetry-focus-bar"><div className="telemetry-focus-project">{focus?<><span>current focus</span><a href={href(focus.project,focus.assignment)}><ProjectIdentity project={focus.project}/></a></>:<span>{ready?'no current focus reported':'loading current focus…'}</span>}</div><button type="button" className="telemetry-edit" aria-label={layout.editing?'done':'edit layout'} title={layout.editing?'save layout':'edit layout'} onClick={layout.editing?layout.finish:layout.start}>{layout.editing?<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg>:<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 4 5 5M4 20l5-1L20 8a2 2 0 0 0-4-4L5 15Z"/></svg>}</button><span className="sr-only" role="status">{layout.message}</span></div>
  <DndContext sensors={layout.sensors} collisionDetection={closestCenter} onDragStart={layout.start} onDragEnd={layout.drop} onDragCancel={layout.cancel}><SortableContext items={layout.order} strategy={rectSortingStrategy}><div className="telemetry-mosaic" data-arranging={layout.editing}>
   {layout.order.map(key=>({
   progress:<MosaicCard key="progress" id="progress" editing={layout.editing}>{layout.editing&&controls('progress')}<FeatureIdentity feature="runner"/><header><Icon kind="play"/><div><h3>today’s progress</h3><p>{known?`${count(model.completed)} completed today · ${count(model.open)} still open`:'Reading current work records…'}</p></div></header><div className="telemetry-progress-body"><Ring percent={ready?percent:null} value={value} caption={ready&&model.total?`${model.completed} of ${model.total} complete`:known?'Partial work records':'No measurable work yet'}/><div className="telemetry-states">{[{kind:'play' as const,count:model.moving.length,display:moving,label:'moving',color:colors[1]},{kind:'pause' as const,count:model.waiting.length,display:waiting,label:'waiting',color:colors[2]}].map(group=><div className="telemetry-state" key={group.label} style={{'--signal':group.color} as CSSProperties}><Icon kind={group.kind}/><div><strong>{count(Math.round(group.display))}</strong> {group.label}<div className="telemetry-meter" aria-label={`${group.count} of ${model.items.length} observed work items ${group.label}`}><span style={{transform:`scaleX(${observed&&model.items.length?group.count/model.items.length:0})`}}/></div></div></div>)}</div></div><p className="telemetry-note">{ready?'Completion recorded in Relay. Includes open work and items completed today.':'Partial records. Counts with + are minimums; the total is not confirmed.'}</p></MosaicCard>,
   needs:<MosaicCard key="needs" id="needs" editing={layout.editing}>{layout.editing&&controls('needs')}<FeatureIdentity feature="inspector"/><header><Icon kind="eye"/><div><h3>needs you</h3><p>{observed?model.needs.length?`${count(model.needs.length)} items need your attention.`:ready?'Nothing is waiting for your input.':'No requests in the records loaded so far.':'Checking requests for your input…'}</p></div><strong className="telemetry-number">{count(Math.round(needs))}</strong></header><div className="telemetry-attention-list">{model.needs.slice(0,2).map(item=><a href={href(item.project,item.assignment)} key={item.project+item.assignment}><i/><div><ProjectIdentity project={item.project}/><WorkerIdentity name={item.primary_staff}/><strong className="telemetry-job-title">{item.goal||item.assignment.replace(/-/g,' ')}</strong><span>{item.waiting_reason||item.next_action}</span></div><b aria-hidden="true">→</b></a>)}{ready&&!model.needs.length&&<div className="telemetry-empty">You’re clear. New requests will appear here.</div>}{model.needs.length>2&&<a className="telemetry-more" href="https://ctrl.loew.fi/#/runner">See all {model.needs.length} requests →</a>}</div></MosaicCard>,
   motion:<MosaicCard key="motion" id="motion" editing={layout.editing}>{layout.editing&&controls('motion')}<header><Icon kind="target"/><div><h3>in motion</h3><p>{observed?`${count(model.projects.length)} ${model.projects.length===1?'product':'products'} with observed activity.`:'Reading product activity…'}</p></div></header><div className="telemetry-motion-body"><div className="telemetry-orbits" aria-label="Products share of observed moving work"><svg viewBox="0 0 220 220" aria-hidden="true">{[94,78,62].map((radius,i)=><g key={radius}><circle className="telemetry-track" cx="110" cy="110" r={radius}/><circle className="telemetry-project-arc" cx="110" cy="110" r={radius} pathLength="100" stroke={colors[i]} opacity={observed&&model.projects[i]?1:0} strokeDasharray={`${observed&&model.projects[i]?model.projects[i].count/model.moving.length*100:0} 100`}/></g>)}</svg><div><strong>{count(Math.round(products))}</strong></div><span className="telemetry-orbit-caption">active {model.projects.length===1?'product':'products'}</span></div><div className="telemetry-projects">{model.projects.slice(0,3).map((item,i)=><a href={href(item.project)} key={item.project}><i style={{background:colors[i]}}/><div><ProjectIdentity project={item.project}/><span>{item.count} moving {item.count===1?'item':'items'}</span></div><b aria-hidden="true">→</b></a>)}{ready&&!model.projects.length&&<p>No current movement reported.</p>}</div></div><p className="telemetry-note">Rings show each product’s share of moving work.</p></MosaicCard>,
   activity:<MosaicCard key="activity" id="activity" editing={layout.editing}>{layout.editing&&controls('activity')}<header><Icon kind="activity"/><div><h3>activity</h3><p>{model.events} observed updates in the last 6 hours.</p></div><strong className="telemetry-number">{Math.round(events)}<small>updates</small></strong></header><div className="telemetry-chart" role="img" aria-label={`Observed updates per half hour, oldest first: ${model.bins.join(', ')}. ${ready?'Current loaded records':'Partial records; coverage incomplete'}.`}><svg viewBox="0 0 588 208"><defs><linearGradient id="telemetry-area" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#f58f76" stopOpacity=".24"/><stop offset="100%" stopColor="#f58f76" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3].map(i=><g key={i}><path className="telemetry-gridline" d={`M32 ${164-i*41.33}H560`}/><text x="6" y={168-i*41.33}>{Math.round(max*i/3)}</text></g>)}<path d={area} fill="url(#telemetry-area)"/><path className="telemetry-chart-line" d={line}/>{points.map(([x,y],i)=><circle key={i} className={i===11&&live&&model.bins[i]>0?'telemetry-latest-point':''} cx={x} cy={y} r={model.bins[i]?3.8:0} fill="#f8d5c9" stroke="#f58f76" strokeWidth="2"/>)}{['6h ago','4h','2h','now'].map((text,i)=><text key={text} x={32+i*176} y="197" textAnchor={i===3?'end':'start'}>{text}</text>)}</svg></div><p className="telemetry-note">{eventConnected?'Connected to live updates.':'Refreshes every minute.'} Source, check and deployment events.</p></MosaicCard>,
   }[key]))}
  </div></SortableContext></DndContext>
 </section>;
}
